# Generated by Django 5.2.7 on 2025-11-02 00:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Unique order number (e.g., ORD-20240115-001)', max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal amount (sum of all items)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='Delivery fee (RedX shipping cost)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (subtotal + delivery_fee)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current order status', max_length=20)),
                ('payment_method', models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('cod', 'Cash on Delivery')], default='sslcommerz', help_text='Payment method used', max_length=20)),
                ('payment_status', models.CharField(default='pending', help_text='Payment status: pending, success, failed, cancelled', max_length=20)),
                ('sslcommerz_session_key', models.CharField(blank=True, help_text='SSLCommerz session key for this transaction', max_length=255, null=True)),
                ('sslcommerz_tran_id', models.CharField(blank=True, help_text='SSLCommerz transaction ID', max_length=100, null=True, unique=True)),
                ('sslcommerz_val_id', models.CharField(blank=True, help_text='SSLCommerz validation ID (after payment success)', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time when payment was completed', null=True)),
                ('recipient_name', models.CharField(help_text="Recipient's full name", max_length=100)),
                ('recipient_phone', models.CharField(help_text="Recipient's phone number", max_length=20)),
                ('recipient_address', models.TextField(help_text='Complete delivery address')),
                ('recipient_city', models.CharField(default='Dhaka', help_text="Recipient's city", max_length=50)),
                ('recipient_area', models.CharField(blank=True, help_text="Recipient's area/zone", max_length=100, null=True)),
                ('recipient_postcode', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('redx_order_id', models.CharField(blank=True, help_text='RedX order/tracking ID', max_length=100, null=True, unique=True)),
                ('redx_tracking_number', models.CharField(blank=True, help_text='RedX tracking number', max_length=100, null=True, unique=True)),
                ('shipping_status', models.CharField(default='pending', help_text='Shipping status from RedX: pending, picked_up, in_transit, delivered', max_length=50)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Date and time when order was shipped', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Date and time when order was delivered', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='Buyer who placed the order', limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order (snapshot)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity * unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='orders_orde_buyer_i_90aa29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sslcommerz_tran_id'], name='orders_orde_sslcomm_026f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['redx_tracking_number'], name='orders_orde_redx_tr_f06714_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
    ]
