# Generated by Django 5.2.7 on 2025-11-02 02:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment/feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='Buyer who wrote the review', limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Order being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Review',
                'verbose_name_plural': 'Order Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_e3e8b1_idx'), models.Index(fields=['buyer'], name='orders_orde_buyer_i_e67519_idx'), models.Index(fields=['rating'], name='orders_orde_rating_d3edf7_idx')],
            },
        ),
    ]
