# Generated by Django 5.2.7 on 2025-11-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product in the wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_users', to='products.product')),
                ('user', models.ForeignKey(help_text='User who added the product to wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wishlist_wi_user_id_ec8321_idx'), models.Index(fields=['product'], name='wishlist_wi_product_1bb998_idx'), models.Index(fields=['user', 'product'], name='wishlist_wi_user_id_2f12fb_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
